# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'DevOpsSC'
    KeyVaultName: 'ghkeyvault02'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DevOpsSC'
    subscriptionId: 'a0cc4ba4-d1a3-4227-a3dc-5557f62a093f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureDevOps'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(LocalAdmin)'
    deploymentMode: 'Incremental'
    deploymentName: 'TemplateDeploy'